version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/design
hooks:
  BeforeInstall:
    - location: deployment/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployment/build_project
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: deployment/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deployment/stop_server
      timeout: 300
      runas: ubuntu