#!/bin/bash
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
apt-get install -y nodejs
apt-get install -y build-essential
apt-get install -y libssl-dev
apt-get install -y libffi-dev
apt-get install -y npm
npm install pm2 -g
rm -rf /home/ubuntu/design
